### PR TITLE
build: update to yfi-sdk 2.0.1

### PR DESCRIPTION
**Pull request by patcito**
includes the fix for hiding new apy in yearly estimates

### CODE REVIEW

**Review by karelianpie — CHANGES_REQUESTED** [review]
`"@yfi/sdk": "2.0.1"` includes a couple of things that would require a bit of testing before upgrading, namely:

* feat: Implement caching for AddressProvider#addressById ([#279](https://github.com/yearn/yearn-sdk/pull/279))
* feat: Supported Zap Vaults [WEB-1424] ([#276](https://github.com/yearn/yearn-sdk/pull/276))

/cc @FoxTheSin

**Comment by xgambitox** [comment]
> `"@yfi/sdk": "2.0.1"` includes a couple of things that would require a bit of testing before upgrading, namely:
> 
> * feat: Implement caching for AddressProvider#addressById ([#279](https://github.com/yearn/yearn-sdk/pull/279))
> * feat: Supported Zap Vaults [WEB-1424] ([#276](https://github.com/yearn/yearn-sdk/pull/276))
> 
> /cc @FoxTheSin

Did some testing, and the only non-retired vaults Im getting that dont support zaps are:

[
    {
        "address": "0x718AbE90777F5B778B52D553a5aBaa148DD0dc5D",
        "name": "Curve alETH Pool yVault"
    },
    {
        "address": "0x8b9C0c24307344B6D7941ab654b2Aeee25347473",
        "name": "Curve EURN Pool yVault"
    },
    {
        "address": "0xd8C620991b8E626C099eAaB29B1E3eEa279763bb",
        "name": "Curve MIM-UST Pool yVault"
    }
]

Could not find them in yearn-meta, so that makes me think that by default, we dont support zaps on vaults that are not yet on yearn-meta (which is a fine approach imo, but we need to be aware of adding them in a more strict process). @FoxTheSin please see if we should add them in yearn-meta and if that enables the zap-in feature.

Rest looks good, and since the above is not an issue from this specific PR, ill approve.

**Review by xgambitox — APPROVED** [review]

**Review by karelianpie — APPROVED** [review]

**Comment by FoxTheSin** [comment]
eth simulations aren't passing (sat for 5 minutes on YFI -> YFI vault, 8 minutes on eth -> rocket curve)

**Comment by FoxTheSin** [comment]
fantom deposit & withdraw looks good

**Comment by FoxTheSin** [comment]
zap simulations passing

**Comment by FoxTheSin** [comment]
aleth and mim-ust available.

EURN couldn't be found.

**Comment by xgambitox** [comment]
> aleth and mim-ust available.
> 
> EURN couldn't be found.

Can you add all of them in yearn-meta, and then try to see if zaps spawn the wallet tx prompt. My guess is it will not work only for EURN since zapper apparently does not support zaps for that particular vault. If it doesnt work, then set `allowZapIn` and `allowZapOut` to false in yearn-meta.

**Comment by turtlemoji** [comment]
@patcito can you bump package minor version? `"version": "1.1.2",`

**Review by turtlemoji — APPROVED** [review]

**Review by xgambitox — APPROVED** [review]

**Pull request merged**
