### PR TITLE
test: simulate tenderly service down [QA]

### PR DESCRIPTION
**Pull request by xgambitox**
## Description

 Simulating Tenderly service not available. Meant for QA only.

## Related Issue

#674 

## Motivation and Context

QA is needed to validate app works as expected when simulations service is not available.

## How Has This Been Tested?

To be tested using the preview build

### CODE REVIEW

**Comment by FoxTheSin** [comment]
testing notes:
https://www.notion.so/yearnfinance/QA-tests-e583c52add3a40aabea7107d4e4c795e?p=bd04b846881348b7853f3e5fb2cc8b94

**Comment by FoxTheSin** [comment]
succesfully completed ftm depo/withdraw
only clicked deposit on eth, didn't run tx

**Comment by FoxTheSin** [comment]
Untitled

**Comment by xgambitox** [comment]
QA done, https://github.com/yearn/yearn-finance-v3/pull/674 merged

**Pull request closed without merging**
