### PR TITLE
fix: order labs by highest apy

### LINKED ISSUE #615: Lab highest apy % are not ordered correctly
Screenshot 2022-04-27 at 17 12 07

yvBoost is in the middle

### PR DESCRIPTION
**Pull request by edwinzhng**
## Description

- Sorts the labs vaults by highest APY when displaying

## Related Issue

Fixes #615

## How Has This Been Tested?

Tested locally by checking the labs page

## Screenshots (if appropriate):

Screen Shot 2022-04-27 at 11 20 34 PM

### CODE REVIEW

**Comment by edwinzhng** [comment]
This will conflict with #561 so I can fix any issues after it gets merged

**Comment by xgambitox** [comment]
What do you think if we handle the sorting in the selector as we do in vaults [here](https://github.com/yearn/yearn-finance-v3/blob/develop/src/core/store/modules/vaults/vaults.selectors.ts#L153) ?

That way if we use the labs recommendations in other place in the future, it will be sorted too

**Comment by edwinzhng** [comment]
thanks! good catch, I can move the sort

**Review by karelianpie — DISMISSED** [review]
LGTM 👍

**Review by karelianpie — APPROVED** [review]

**Pull request merged**
