### PR TITLE
fix: always show eth

### PR DESCRIPTION
**Pull request by FiboApe**
Need to be merged after release of https://github.com/yearn/yearn-sdk/pull/278

### CODE REVIEW

**Comment by xgambitox** [comment]
Since we should expect same issue to happen in other networks, we should refactor in other PR all the app where we use ETH address directly, and use from now on `0x00...` as native token address.

**Review by turtlemoji — APPROVED** [review]

**Comment by turtlemoji** [comment]
hold until SDK release

**Comment by FoxTheSin** [comment]
functionality appears good but UI stuff is old

**Comment by FiboApe** [comment]
Closing this in favor of #584

**Pull request closed without merging**
