### PR TITLE
Add Chinese translation for "portfolio"

### PR DESCRIPTION
**Pull request by maraoz**
## Description

I attempted to contribute to Chinese site translation. Not sure if this is the correct way. 

If this works, I can continue with other missing i18n strings.

## How Has This Been Tested?

I run the app locally and saw the change was working.

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by FoxTheSin** [comment]
ping'd qosmonot

**Comment by qosmonot** [comment]
checked and approved by @Bee from yTranslations

**Comment by turtlemoji** [comment]
The current files are outdated with the latest translates. I will update to all latest locales and then report here

**Comment by turtlemoji** [comment]
Contributing in the .json files is ok! It is just that we are not in sync now with the internal dev files in locsize.

- Powered by TurtleDeepMind AI

**Comment by turtlemoji** [comment]
@maraoz the key was added on internal locales so I will close the PR, updated here:
https://github.com/yearn/yearn-finance-v3/pull/621

Thank you tho for spotting it!

**Comment by turtlemoji** [comment]
> @turtlemoji awesome! is this (opening a PR) the right way to contribute additional Chinese translations?

Yep! It is!

**Pull request closed without merging**
