### PR TITLE
fix: Yield under modal displaying 0

### PR DESCRIPTION
**Pull request by karelianpie**
Fixes https://github.com/yearn/yearn-finance-v3/issues/493

Uses the util function and finds the type (e.g "new") from the apy metadata

### CODE REVIEW

**Comment by karelianpie** [comment]
It appears that the team is working on a solution to fix the 0.00% in the case of yvBOOST vault (https://t.me/c/1152055703/21767), the fix in this current PR will work for vaults that have `apyType === "new"`

**Comment by gotzenx** [comment]
This fix should also be implemented on `DepositTx` component to impact the vaults deposits modal and not only the labs deposits modal. Right?

**Comment by xgambitox** [comment]
as @gotzenx says, lets add the fix to `DepositTx` component too

**Comment by karelianpie** [comment]
@gotzenx @xgambitox added the `formatApy` to `DepositTx` with https://github.com/yearn/yearn-finance-v3/pull/504/commits/26427afde6ce2e686b54af6ea425e434ad57bf54

Made `apyType` optional so we don't need to pass it as metadata is optional with https://github.com/yearn/yearn-finance-v3/pull/504/commits/ac1d18cfc07f85cea6c90c08031b14c49e17e72a

**Review by xgambitox — APPROVED** [review]

**Pull request merged**
